name: APPTR
on:
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  format:
    name: formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/formatting@v2

  lint:
    name: linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/linting@v2

  images:
    name: images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/images@v2
        with:
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: acm-ucr/build@v2
